# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tmuxinator"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Allen Bargi"]
  s.date = "2012-09-09"
  s.description = "Create and manage complex tmux sessions easily."
  s.email = "allen.bargi@gmail.com"
  s.executables = ["mux", "tmuxinator", "tmuxinator_completion"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/mux",
    "bin/tmuxinator",
    "bin/tmuxinator_completion",
    "lib/tmuxinator.rb",
    "lib/tmuxinator/assets/sample.yml",
    "lib/tmuxinator/assets/tmux_config.tmux",
    "lib/tmuxinator/cli.rb",
    "lib/tmuxinator/config_writer.rb",
    "lib/tmuxinator/helper.rb",
    "spec/spec_helper.rb",
    "spec/tmuxinator_spec.rb",
    "tmuxinator.gemspec"
  ]
  s.homepage = "http://github.com/aziz/tmuxinator"
  s.licenses = ["MIT"]
  s.post_install_message = "\n  __________________________________________________________\n  ..........................................................\n\n  Thank you for installing tmuxinator\n  Please be sure to to drop a line in your ~/.bashrc file, similar\n  to RVM if you've used that before:\n\n  [[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator\n\n  also ensure that you've set these variables in your ENV:\n\n  $EDITOR, $SHELL\n\n  you can run `tmuxinator doctor` to make sure everything is set.\n  happy tmuxing with tmuxinator!\n\n  ..........................................................\n  __________________________________________________________\n\n  "
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Create and manage complex tmux sessions easily."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

