// Package commands implements all tmuxinator CLI commands.
package commands

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/tmuxinator/tmuxinator/internal/config"
	"github.com/tmuxinator/tmuxinator/internal/template"
	"github.com/tmuxinator/tmuxinator/internal/tmux"
)

// NewDebugCmd creates the `debug` command.
func NewDebugCmd() *cobra.Command {
	var (
		attach        bool
		noAttach      bool
		customName    string
		projectConfig string
		appendMode    bool
		noPreWindow   bool
	)

	cmd := &cobra.Command{
		Use:   "debug [PROJECT] [ARGS...]",
		Short: "Output the shell commands that are generated by tmuxinator",
		RunE: func(cmd *cobra.Command, args []string) error {
			name, projectArgs := extractNameAndArgs(args, projectConfig)
			forceAttach, forceDetach := resolveAttachFlags(resolveAttach(cmd, attach, noAttach))

			project, err := config.ValidateProject(config.ValidateOptions{
				Name:          name,
				ProjectConfig: projectConfig,
				CustomName:    customName,
				ForceAttach:   forceAttach,
				ForceDetach:   forceDetach,
				Append:        appendMode,
				NoPreWindow:   noPreWindow,
				Args:          projectArgs,
			})
			if err != nil {
				return err
			}

			script, err := template.RenderStart(project)
			if err != nil {
				return err
			}

			fmt.Fprint(os.Stdout, script)
			return nil
		},
	}

	cmd.Flags().BoolVarP(&attach, "attach", "a", false, "Attach to tmux session after creation")
	cmd.Flags().BoolVar(&noAttach, "no-attach", false, "Do not attach to tmux session")
	cmd.Flags().StringVarP(&customName, "name", "n", "", "Give the session a different name")
	cmd.Flags().StringVarP(&projectConfig, "project-config", "p", "", "Path to project config file")
	cmd.Flags().BoolVar(&appendMode, "append", false, "Append windows to current session")
	cmd.Flags().BoolVar(&noPreWindow, "no-pre-window", false, "Skip pre_window commands")

	return cmd
}

// printVersionWarning prints the unsupported tmux version warning and waits for ENTER.
func printVersionWarning() {
	fmt.Fprintln(os.Stderr, tmux.UnsupportedVersionMsg)
	fmt.Fprint(os.Stderr, "\nPress ENTER to continue.")
	fmt.Scanln()
}

