// Package commands implements all tmuxinator CLI commands.
package commands

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/tmuxinator/tmuxinator/internal/config"
	"github.com/tmuxinator/tmuxinator/internal/tmux"
)

// NewListCmd creates the `list` command.
func NewListCmd() *cobra.Command {
	var (
		newline bool
		active  bool
	)

	cmd := &cobra.Command{
		Use:     "list",
		Short:   "Lists all tmuxinator projects",
		Aliases: []string{"l", "ls"},
		RunE: func(cmd *cobra.Command, args []string) error {
			activeFilter := ""
			if cmd.Flags().Changed("active") {
				if active {
					activeFilter = "true"
				} else {
					activeFilter = "false"
				}
			}

			sessions := tmux.ActiveSessions()
			configs := config.Configs(activeFilter, sessions)

			fmt.Println("tmuxinator projects:")
			if newline {
				for _, c := range configs {
					fmt.Println(c)
				}
			} else {
				printInColumns(configs)
			}
			return nil
		},
	}

	cmd.Flags().BoolVarP(&newline, "newline", "n", false, "Force output to be one entry per line")
	cmd.Flags().BoolVarP(&active, "active", "a", false, "Filter output by active project sessions")
	return cmd
}

// printInColumns prints a list of strings in columns (like Ruby's print_in_columns).
func printInColumns(items []string) {
	if len(items) == 0 {
		return
	}
	// Find the longest item
	maxLen := 0
	for _, item := range items {
		if len(item) > maxLen {
			maxLen = len(item)
		}
	}
	colWidth := maxLen + 2
	termWidth := 80 // assume 80 columns
	cols := termWidth / colWidth
	if cols < 1 {
		cols = 1
	}

	for i, item := range items {
		fmt.Printf("%-*s", colWidth, item)
		if (i+1)%cols == 0 {
			fmt.Println()
		}
	}
	if len(items)%cols != 0 {
		fmt.Println()
	}
}

// NewCommandsCmd creates the `commands` command.
func NewCommandsCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "commands [shell]",
		Short: "Lists commands available in tmuxinator",
		Run: func(cmd *cobra.Command, args []string) {
			shell := ""
			if len(args) > 0 {
				shell = args[0]
			}
			printCommands(shell)
		},
	}
}

var commandDescriptions = map[string]string{
	"commands":    "Lists commands available in tmuxinator",
	"completions": "Used for shell completion",
	"copy":        "Copy an existing project to a new project and open it in your editor",
	"debug":       "Output the shell commands that are generated by tmuxinator",
	"delete":      "Deletes given project",
	"doctor":      "Look for problems in your configuration",
	"edit":        "Edit an existing project file in your editor",
	"help":        "Shows help for a specific command",
	"implode":     "Deletes all tmuxinator projects",
	"local":       "Start a tmux session using ./.tmuxinator.y[a]ml",
	"list":        "Lists all tmuxinator projects",
	"new":         "Create a new project file and open it in your editor",
	"open":        "Create or open a project file in your editor",
	"start":       "Start a tmux session using a project's name or a path to a project config file",
	"stop":        "Stop a tmux session using a project's tmuxinator config",
	"stop-all":    "Stop all tmux sessions which are using tmuxinator projects",
	"version":     "Display installed tmuxinator version",
}

func printCommands(shell string) {
	keys := make([]string, 0, len(commandDescriptions))
	for k := range commandDescriptions {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if shell == "zsh" {
		for _, k := range keys {
			fmt.Printf("%s:%s\n", k, commandDescriptions[k])
		}
	} else {
		fmt.Println(strings.Join(keys, "\n"))
	}
}

// NewCompletionsCmd creates the `completions` command.
func NewCompletionsCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "completions [arg]",
		Short: "Used for shell completion",
		Run: func(cmd *cobra.Command, args []string) {
			if len(args) == 0 {
				return
			}
			arg := args[0]
			switch arg {
			case "start", "stop", "edit", "open", "copy", "delete":
				sessions := tmux.ActiveSessions()
				configs := config.Configs("", sessions)
				for _, c := range configs {
					fmt.Println(c)
				}
			}
		},
	}
}

